print("Different escape characters include:")
print("\\' which can be used to print the \' character")
print("\\\" which can be used to print the \" character")
print("\\t which can be used to print a \t tab ")
print("\\n which can be used to print a \n newline")
print("And finally \\\\ which can be used to print the \\ character")
print()
print()
print("if you put the letter r before a string like this r\"string\"")
print(r"You are able to put any characters you \ like without \n \t \ having to escape them")
print("The 'r' stands for 'raw'")
print()
print()
print("I am now going to define a variable called a and give it the value 3")
a = 3
print(r"If i use an \"f string\" i can insert the variable with curly braces")
print(r"a is equal to {a}")
print(f"a is equal to {a}")